"""Migración desde Codespaces

Revision ID: d91e7727cccc
Revises: 6b2fc563d750
Create Date: 2025-08-12 02:42:32.008441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91e7727cccc'
down_revision = '6b2fc563d750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('contrato',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('contrato',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
